version: '3'

services:
  #Image for php
  web:
    build:
      context: ./images/php
    container_name: php
    restart: unless-stopped
    volumes:
      - ./www:/var/www
      - ./src:/var/src
      - ./templates:/var/templates
    networks:
      - php-nginx-postgres-network

  #Image for proxy server
  proxy:
    build:
      context: ./images/proxy
    container_name: proxy
    image: nginx
    restart: unless-stopped
    ports:
      - ${WEB_PORT:-80}:80
      - "443:443"
    depends_on:
      - web
      - adminer
    volumes:
      - ./:/var/www
      - ./images/proxy/:/etc/nginx/conf.d/
    networks:
      - php-nginx-postgres-network

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminer
    environment:
      - PMA_HOST=db
      - PMA_ABSOLUTE_URI=http://localhost:80/adminer
    depends_on:
      - db
    networks:
      - php-nginx-postgres-network

  db:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-db}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD:-password}
      POSTGRES_USER: ${USER_LOGIN:-login}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgres
    networks:
      - php-nginx-postgres-network

volumes:
  dbdata:
    driver: local

networks:
  php-nginx-postgres-network:
    driver: bridge